import { expect, test } from '@playwright/test'

for (const size of [{ name: 'mobile', width: 428, height: 926 }, { name: 'desktop', width: 1280, height: 900 }, { name: 'zoom', width: 320, height: 740 }]) {
  test(`design system and core flow: ${size.name}`, async ({ page }) => {
    await page.setViewportSize(size)
    await page.goto('./')
    const welcome = page.getByRole('button', { name: 'Начать знакомство', exact: true })
    if (await welcome.count()) await welcome.click()
    if (size.name === 'zoom') await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
    const checkLayout = async () => {
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
      for (const button of await page.getByRole('button').all()) {
        const bounds = await button.boundingBox()
        if (bounds) { expect(bounds.width).toBeGreaterThanOrEqual(48); expect(bounds.height).toBeGreaterThanOrEqual(48) }
      }
    }
    await expect(page.getByLabel('Ответ на пример')).toHaveAttribute('placeholder', 'Введи целое число от 0 до 100')
    const placeholder = page.locator('.answer-field__placeholder')
    await expect(placeholder).toHaveText('Введи целое число от 0 до 100')
    const hintBounds = await placeholder.boundingBox()
    const inputBounds = await page.getByLabel('Ответ на пример').boundingBox()
    expect(hintBounds).not.toBeNull()
    expect(inputBounds).not.toBeNull()
    expect(hintBounds!.width).toBeLessThanOrEqual(inputBounds!.width)
    expect(hintBounds!.height).toBeLessThanOrEqual(inputBounds!.height)
    await page.screenshot({ path: `/tmp/math-ui-answer-placeholder-${size.name}.png`, fullPage: true })
    await page.getByRole('heading', { name: 'Короткая проверка', exact: true }).click()
    await expect(page.getByLabel('Ответ на пример')).not.toBeFocused()
    await page.screenshot({ path: `/tmp/math-ui-field-rest-${size.name}.png`, fullPage: true })
    await page.getByLabel('Ответ на пример').fill('abc')
    await expect(placeholder).toHaveCount(0)
    await page.getByRole('button', { name: 'Далее', exact: true }).click()
    await expect(page.getByLabel('Ответ на пример')).toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('.answer-field__error')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
    await checkLayout()
    await page.screenshot({ path: `/tmp/math-ui-diagnostic-${size.name}.png`, fullPage: true })
    await page.getByLabel('Ответ на пример').fill('9')
    await expect(page.getByLabel('Ответ на пример')).not.toHaveAttribute('aria-invalid', 'true')
    await expect(page.locator('.answer-field__error')).toHaveCount(0)
    await expect(page.getByLabel('Ответ на пример')).toHaveAttribute('aria-describedby', 'answer-help')
    await page.getByRole('button', { name: 'Пропустить проверку' }).click()
    await expect(page.getByRole('heading', { name: 'Умножайка' })).toBeFocused()
    await checkLayout()
    await page.evaluate(() => window.scrollTo(0, 0))
    const launchBounds = await page.getByRole('button', { name: 'Играть', exact: true }).boundingBox()
    const knowledgeBounds = await page.getByRole('region', { name: 'Звёзды знаний', exact: true }).boundingBox()
    expect(launchBounds!.y + launchBounds!.height).toBeLessThan(knowledgeBounds!.y)
    if (size.name !== 'zoom') {
      expect(launchBounds!.y + launchBounds!.height).toBeLessThanOrEqual(size.height)
    }
    const stage = await page.locator('.home__route .xp-route__map').boundingBox()
    expect(stage).not.toBeNull()
    for (const art of await page.locator('.home__route .xp-route__map image').all()) {
      const bounds = await art.boundingBox()
      expect(bounds).not.toBeNull()
      expect(bounds!.x).toBeGreaterThanOrEqual(stage!.x)
      expect(bounds!.y).toBeGreaterThanOrEqual(stage!.y)
      expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(stage!.x + stage!.width)
      expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(stage!.y + stage!.height)
    }
    await page.screenshot({ path: `/tmp/math-ui-home-${size.name}.png`, fullPage: true })
    await page.screenshot({ path: `/tmp/math-ui-home-first-viewport-${size.name}.png` })
    await page.locator('.home__route').screenshot({ path: `/tmp/math-ui-route-${size.name}.png` })
    await page.getByRole('button', { name: 'Играть', exact: true }).click()
    for (let index = 0; index < 2; index++) {
      await page.getByRole('button', { name: 'Не знаю', exact: true }).click()
      await expect(page.getByRole('button', { name: 'Продолжить', exact: true })).toBeFocused()
      await checkLayout()
      await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
    }
    await expect(page.getByText('Миссия завершена!', { exact: true })).toBeVisible()
    await expect(page.getByText('+0 XP', { exact: true })).toBeVisible()
    await expect(page.getByText('Звёзды знаний: 0 из 66')).toBeVisible()
    await expect(page.getByText('Всего 0 XP · уровень 1')).toBeVisible()
    await checkLayout()
    await expect(page.locator('.xp-award__reason')).toContainText('даже ошибка считается попыткой')
    await expect(page.locator('.inspira-confetti')).toHaveCount(0)
    await page.locator('.mission__finish').evaluate(element => element.getAnimations({ subtree: true }).filter(animation => animation.effect?.getComputedTiming().iterations !== Infinity).forEach(animation => animation.finish()))
    await page.screenshot({ path: `/tmp/math-ui-summary-${size.name}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Карта звёзд' }).click()
    await expect(page.getByRole('heading', { name: 'Карта звёзд' })).toBeVisible()
    await expect(page.getByText('Открыто звёзд: 0 из 66')).toBeVisible()
    await expect(page.locator('.map__intro')).toContainText('XP на звёзды не влияют.')
    const factsToggle = page.getByRole('button', { name: /Все факты и достижения/ })
    await expect(factsToggle).toHaveAttribute('aria-expanded', 'false')
    await factsToggle.click()
    await expect(factsToggle).toHaveAttribute('aria-expanded', 'true')
    await expect(page.getByRole('list', { name: 'Достижения по каждому факту' }).getByRole('listitem')).toHaveCount(66)
    await checkLayout()
    await page.locator('.map__archive-content').evaluate((element) => element.getAnimations().forEach((animation) => animation.finish()))
    await page.screenshot({ path: `/tmp/math-ui-map-expanded-${size.name}.png` })
    await factsToggle.click()
    await expect(page.getByRole('list', { name: 'Достижения по каждому факту' })).toHaveCount(0)
    await page.locator('.map__archive-chevron').evaluate((element) => element.getAnimations().forEach((animation) => animation.finish()))
    await page.screenshot({ path: `/tmp/math-ui-map-${size.name}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Назад', exact: true }).click()
    await page.getByRole('button', { name: 'Отчёт для взрослого' }).click()
    await page.getByRole('button', { name: 'Сбросить данные', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Удалить весь прогресс?' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Отмена', exact: true })).toBeFocused()
    await checkLayout()
    await page.screenshot({ path: `/tmp/math-ui-reset-dialog-${size.name}.png`, fullPage: true })
    await page.getByRole('button', { name: 'Отмена', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await checkLayout()
    await page.screenshot({ path: `/tmp/math-ui-report-${size.name}.png`, fullPage: true })
  })
}
